### ISSUE TITLE
Can't work in gamelift mode

### ISSUE THREAD

**Issue by thanksfromleo** [aws-samples/amazon-gamelift-unity#9] opened 2020-03-30 03:25 UTC
Hello, AWS gamelift Team. I am a new gamelifter to study how to use gamelift tech in my real-time fps game project. After following the doc step by step, LOCAL MODE worked, and then try connect aws gamelift server, there get stuck and detail attached.

1、My OS is Windows 10 Home Edition, it contains .net frame 4.5 yet, but when i run the build.bat, it prompt a message tell me here need .net framework 4.5 dev pack, how can i get it, i googled but no result. (pic 1)

2、So i edit the "/DeployTool/DeployTool.csproj", modify <TargetFrameworkVersion>v4.5</TargetFrameworkVersion> to 4.5.1, install .net framework 4.5.1 dev pack, reset my Unity install path, cool LOCAL MODE worked.

3、I create a new IAM user, grant it the "gamelift client" and "gamelift server" permission policies, deploy gamelift to aws server, download the credentials.csv to my local machine, run rc to start Unity project, it encounter a fatal error and can't proceed any more.

![fatal to start aws client](https://user-images.githubusercontent.com/1563846/77872068-799a0380-7278-11ea-89a0-bdd19bec191d.png)

Some screen shot may give you more imformation, thank you very much!

![net45notfound](https://user-images.githubusercontent.com/1563846/77871327-5d956280-7276-11ea-98cd-7a50d6cc1599.png) (pic 1)

![IAM user](https://user-images.githubusercontent.com/1563846/77871394-91708800-7276-11ea-8687-163a6fb491f7.png) (iam user and permissions policies)

![gamelift-client](https://user-images.githubusercontent.com/1563846/77871474-d0064280-7276-11ea-8422-8cfbadd534b3.png)
![gamelift-server](https://user-images.githubusercontent.com/1563846/77871481-d3013300-7276-11ea-970c-b0ad356e0d0a.png)

![credentials](https://user-images.githubusercontent.com/1563846/77871831-e2cd4700-7277-11ea-9a88-47455ba005f8.png)
![alias](https://user-images.githubusercontent.com/1563846/77872201-e0b7b800-7278-11ea-88be-c9334a2f2411.png)

(for convenient test, i hard code the keys in code)

![aws server](https://user-images.githubusercontent.com/1563846/77871976-45bede00-7278-11ea-8c7b-73ada7be95eb.png)

**Comment by alanmur** [comment] 2020-03-31 22:46
Hello Leo!

I am sorry to hear that you have encountered a problem. I will work with you to resolve as quickly as possible.

This looks like a possible duplicate of #8. This has not been merged as the fix has not been verified independently.

I have made some modifications to the way that credentials are handled in the project. Please go to https://github.com/aws-samples/amazon-gamelift-unity/tree/credfix and there you will find a branch (credfix) that I believe will fix your problem. How to use:

Get the credfix branch, which will change three files. [Note that the standalone player log may have moved location.]

Build the client as discussed in the instructions.

Run the client with rc --credentials to load the credentials.

Attach the Player.log file for me to look at. Also it should work for you! Let me know, and if we are good I will merge the changes.

**Comment by alanmur** [comment] 2020-04-16 16:59
Hello! Did the suggested solution work for you?

**Comment by thanksfromleo** [comment] 2020-04-18 02:41
Hello~ Sorry for late here. Very thanks for your&nbsp;detailed reply, for some reason, we choose another&nbsp;solution to&nbsp;implement our game. Gamelift is amazing for&nbsp;modern game develop, i will&nbsp;keep attention to it and expect it become better and better in the feature!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Al Murray"<notifications@github.com&gt;; 
发送时间: 2020年4月17日(星期五) 凌晨1:00
收件人: "aws-samples/amazon-gamelift-unity"<amazon-gamelift-unity@noreply.github.com&gt;; 
抄送: "Leo"<thanksfromleo@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [aws-samples/amazon-gamelift-unity] Can&#39;t work in gamelift mode (#9)





 
Hello! Did the suggested solution work for you?
 
&mdash;

**Closed** 2020-04-20 16:58 UTC
